### ISSUE TITLE
realpath is dead

### ISSUE THREAD

**Issue by barbazul** [netz98/n98-deployer#3]
The realpath command is not being distributed in most up to date versions of almost every major linux distribution (at least this seems to be the case for the Debian and RHEL families).

It is being used in `N98\Deployer\Task\DeployTasks::initStableRelease()` to determine the current stable release (the target of the current symlink)

I have worked around this issue by aliasing `realpath` to `readlink -f` but you should probably consider updating the code as well

**Comment by cmuench** [comment]
@mwr I have the same problem for my actual deployment. I replaced "realpath" with "readlink -f" and it works for.
