### ISSUE TITLE
Where does the cms:import command come from?

### ISSUE THREAD

**Issue by barbazul** [netz98/n98-deployer#7]
I noticed there is a MagentoTask to import CMS content. however, there is no cms:import command in Magento CLI and I couldn't find any reference to it by googling.

https://github.com/netz98/n98-deployer/blob/df9c6690ed91011d453c69b64fbacb9febd66925/src/Deployer/Task/MagentoTasks.php#L177

Is this a custom proprietary module or is it based on a published library that I simply missed to locate in the internets?

thank you

**Comment by shuryoka** [comment]
Sorry for the late answer. This is a command of a module we are typically using in our projects. It allows us to import or update CMS blocks via XML. So yes, it's not a default command of Magento 2 in any yet available version.
